version: 1.0.{build}

image: Visual Studio 2017
shallow_clone: true

matrix:
    fast_finish: true

platform:
    -x64

install:
    set PATH=%PATH%;C:\msys64\bin;C:\msys64\usr\bin

build_script:
    - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syu"
    - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S make base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-openssl"
    - Ä†:\msys64\usr\bin\make QT_PATH="C:\Qt\5.13.0\mingw73_64"

